config: SalishSea1500
runid: RUN120

# --- DOMAIN GEOMETRY
file_bathy:  /project/6006412/mdunphy/Forcing/grid/bathy_salishsea_1500m_20210706.nc
file_coord: /project/6006412/mdunphy/Forcing/grid/coordinates_salishsea_1500m.nc
file_mesh:  /project/6006412/mdunphy/Forcing/grid/mesh_mask_20210406.nc

obs:
    root: /project/6006412/goldford/OBS-WEST
    name: "OBS-WEST"

output_path: /project/6006412/goldford/ANALYSIS/SalishSea1500-RUN120

src_output_dir: /project/6006412/mdunphy/nemo_results/SalishSea1500/SalishSea1500-RUN120/CDF
time_getter: cmc_start_end

plot:
    map:
        xlim: [-126, -122]
        ylim: [47, 51]

    #file_formats: ['png', 'pdf', 'svg']
    file_formats: ['png']


analysis:
    periods:
        year2016: [2016-01-01, 2017-01-01]
        year2017: [2017-01-01, 2018-01-01]
        #year2018: [2018-01-01, 2019-01-01]
    domains:
      SalishSea1500: /home/mid002/WORK4/SalishSea1500/coordinates_salishsea_1500m.nc

    CTD:
        # CTD analysis bits, to be reorganized
        domain_file: CTD_analysis_domain_config_template-SalishSea.yml


extract:

    SST:
        pattern: '*_1h_grid_T_[0-9][0-9]*'
        temperature: 'votemper'
        time_var: time_counter
    MCTD:
        pattern: '*_1d_grid_T_[0-9][0-9]*'
        temperature: 'votemper'
        salinity: 'vosaline'
        time_var: time_counter
        exclude: ["*/EF04_*"]
    CTD:
        pattern: '*_1d_grid_T_[0-9][0-9]*'
        temperature: 'votemper'
        salinity: 'vosaline'
        time_var: time_counter
    CMCSST:
        pattern_daily: '*_1d_grid_T_[0-9][0-9]*'
        pattern_hourly: '*_1h_grid_T_[0-9][0-9]*'
        temperature: 'votemper'
        time_var: time_counter
