config: CIOPSW
runid: BC12

# --- DOMAIN GEOMETRY
file_bathy: /home/mid002/WORK4/CIOPS-W-GRID/Bathymetry_NEP36_714x1020_SRTM30v11_NOAA3sec_WCTSS_JdeFSalSea.nc
file_coord: /home/mid002/WORK4/CIOPS-W-GRID/coordinates_NEP36_714x1020.nc
file_mesh: /home/mid002/WORK4/CIOPS-W-GRID/mesh_mask_Bathymetry_NEP36_714x1020_SRTM30v11_NOAA3sec_WCTSS_JdeFSalSea.nc

obs:
    root: /home/sdfo600/DATA/OBS-WEST
    name: "OBS-WEST"

output_path: /home/mid002/WORK4/SalishSea1500/ANALYSIS/CIOPSW-BC12

src_output_dir: /gpfs/fs4/dfo/dpnm/dfo_dpnm/sdfo600/RUNS/CIOPS-W/pa_w_r1.5_bc12
time_getter: cmc_start_end
start_date: '20151122'
final_date: '20190921'


# CIOPSW-specific plotting options overrides
plot:
    map:
      xlim: [-142, -120]
      ylim: [44, 60]



analysis:
    periods:
        year2016: [2016-01-01, 2017-01-01]
        year2017: [2017-01-01, 2018-01-01]
        year2018: [2018-01-01, 2019-01-01]
    domains:
        CIOPSW: /home/mid002/WORK4/CIOPS-W-GRID/mesh_mask_Bathymetry_NEP36_714x1020_SRTM30v11_NOAA3sec_WCTSS_JdeFSalSea.nc
        SalishSea: /home/mid002/WORK4/MEOPAR/grid/coordinates_seagrid_SalishSea201702.nc

    CTD:
        domain_file: CTD_analysis_domain_config_template-SalishSea.yml
    TDL:
        wtdir: /home/mid002/WORK4/Datasets/WebTide/ne_pac4/
        wtname: ne_pac4

extract:
    TG:
        pattern: '*_1h_grid_T_2D_*'
        ssh: 'zos'
        ib: 'ssh_ib'
        exclude: ["*Vancouver*Harbour*","*New*Westminster*","*/Steveston*"]
    HTG:
        pattern: '*_1h_grid_T_2D_*'
        ssh: 'zos'
        exclude: ["*/07024const*", "*/07060const*", "*/07196const*",
                  "*/07107const*", "*/07121const*", "*/07122const*", "*/07123const*", "*/07124const*", "*/07125const*",
                  "*/07370const*",
                  "*/07710const*", "*/07771const*", "*/07843const*", "*/07844const*",
                  "*/07852const*", "*/07860const*",
                  "*/08095const*", "*/08107const*",
                  "*/08079const*", "*/08087const*", "*/08104const*", "*/08105const*", "*/08110const*",
                  "*/07442const*", "*/07824const*", "*/07542const*", "*/07861const*",
                  "*/07194const*", "*/07215const*", "*/07240const*", "*/07842const*"]
    SST:
        pattern: '*_1h_grid_T_2D_*'
        temperature: 'tos'
    MCTD:
        pattern: '*_1d_grid_T_[0-9][0-9]*'
        time_offset: -43200
        temperature: 'thetao'
        salinity: 'so'
        exclude: ["*/SOGN2_CTD_2016-07_2017-04_320m.nc",    # These fail to extract; excluding until we have time to revisit why
                  "*/SILL_CTD_2016-01_2019-10_90m.nc",
                  "*/SOGN2-C_CTD_2015-10_2016-07_330m.nc",
                  "*/BDYPM_CTD_2016-01_2019-08_220m.nc",
                  "*/KVIPC2*" ]


    CMCSST:
        pattern_daily: '*_1d_grid_T_[0-9][0-9]*'
        time_offset: -43200
        temperature: 'thetao'
    CTD:
        pattern: '*_1d_grid_T_[0-9][0-9]*'
        time_offset: -43200
        temperature: 'thetao'
        salinity: 'so'
    TDL:
        pattern: '*_1h_grid_T_2D_*'
        ssh: 'zos'
        patternu: '*_1h_grid_U_2D_*'
        ubt: 'ubar'
        patternv: '*_1h_grid_V_2D_*'
        vbt: 'vbar'
    CM:
        pattern: '*_1h_*-09_*-*.nc'   # 9 grid point exports, u,v combined
        uvel: 'uo'
        vvel: 'vo'
    ADCP:
        pattern: '*_1h_*-09_*-*.nc'   # 9 grid point exports, u,v combined
        uvel: 'uo'
        vvel: 'vo'
        exclude: ["*/DEV*",
                  '*/FolgerPassage_ADCP_2015-09_2016-03_22m*',
                  '*/BarkleyCanyon*',
                  '*/BoundaryPass*',
                  '*JuandeFucaStrait_ADCP_2016-10_2017-04_55m*',
                  '*ClayoquotSlope_ADCP_2017-06_2018-05_1242m*',
                  '*Endeavour_ADCP_2017-06_2018-05_2191m*',
                  '*JuandeFucaStrait_ADCP_2017-04_2017-11_114m*']
    FERRY:
        pattern: '*_1h_grid_T_2D*'
        temperature: 'tos'
        salinity: 'sos'
