# List of users and user-specific runtime settings
  # 'texlive' is the location of your texlive installation for report generation
  # 'CONDA_SCRIPT' is the path to conda.sh in your anaconda or miniconda installation (needed only for submitted tasks)
  # 'project' is the project name for jobsub (needed only for submitted tasks)
mid002:
  texlive: /home/mid002/Software/texlive/2020
  CONDA_SCRIPT: /home/mid002/WORK7/anaconda3/etc/profile.d/conda.sh
  project: dfo_dpnm_ss
